baseURL = 'https://ryanabx.github.io/'
languageCode = 'en-us'
title = "Ryan Brue's Website"
theme = 'ananke'

SectionPagesMenu = "main"

[params]
favicon = "images/logo.png"
description = "Ryan Brue's Website and Blog"
facebook = ""
twitter = ""
instagram = ""
youtube = ""
github = "ryanabx"
gitlab = "ryanabx"
linkedin = "ryanbrue"
mastodon = "ryanabx@mastodon.social"
recent_posts_number = 3
site_logo = "images/logo.png"